#
###################################
# Site wide configuration
####################################
#
title: Didática Zero!!
email: palexandremello@gmail.com
description: Ensinando e aprendendo programação, e aplicando na meteorologia
url: https://palexandremello.github.io # the base hostname & protocol for your site
keywords: ["Programming", "Weather","Meteorology","Python","Technology"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Brasilia
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Paulo Alexandre
  avatar: avatar.jpgc
  job: "Estudante"
  bio: "Futuro bacharel em Meteorologia, entusiasta em programação. Pelotas, Brasil."
  email: palexandremello@gmail.com
  disqus-shortname: #renyuanzblog
  twitter: #renyuan814 #username
  facebook: #username
  google:
    plus: #username
    analytics: #UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: palexandremello #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: paulo-alexandre-mello-2a628b98 #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
